parameters:
  - name: config
    displayName: Configuration
    type: string
    default: Release
    values:
      - Release
      - Debug
  - name: specVersion
    displayName: Specifications Version
    type: string
    default: e2-beta-10-update-2.1
    values:
      - e2-beta-10-update-2.1
      - e2-beta-10-update-2
      - e2-beta-10-update-1
      - e2-beta-9-update-2
      - e2-beta-9-update-1
      - e2-beta-8-update-3
      - e2-beta-8-update-2
      - e2-beta-8-update-1
      - e2-beta-8-update-0
  - name: Library_Branch
    displayName: Library Branch
    type: string
    default: master
  - name: Build_Branch
    displayName: Build Branch
    type: string
    default: master
  - name: Utilities_Branch
    displayName: Utilities Branch
    type: string
    default: master
  - name: Devops_Branch
    displayName: DEVOPS Branch
    type: string
    default: master
  - name: Demos_Branch
    displayName: Demos Branch
    type: string
    default: master
  - name: Tools_Branch
    displayName: Tools Branch
    type: string
    default: master
  - name: Test_Branch
    displayName: Test Branch
    type: string
    default: master
  - name: Documentation_Branch
    displayName: Documentation Branch
    type: string
    default: master

resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: codeway/templates
      endpoint: ghe
    - repository: specifications
      type: githubenterprise
      name: extensibility-2-0/e2-service-specifications
      endpoint: ghe
      ref: refs/tags/${{ parameters.specVersion }}
    - repository: oxpd2-libraries
      type: githubenterprise
      name: extensibility-2-0/oxpd2-libraries
      ref: ${{ parameters.Library_Branch }}
      endpoint: ghe
    - repository: utilities
      type: githubenterprise
      name: extensibility-2-0/utilities
      endpoint: ghe
      ref: ${{ parameters.Utilities_Branch }}
    - repository: devops
      type: githubenterprise
      name: extensibility-2-0/devops
      endpoint: ghe
      ref: ${{ parameters.Devops_Branch }}
    - repository: build
      type: githubenterprise
      name: extensibility-2-0/build
      endpoint: ghe
      ref: ${{ parameters.Build_Branch }}
    - repository: oxpd2-examples
      type: githubenterprise
      name: extensibility-2-0/oxpd2-examples
      endpoint: ghe
      ref: $(Build.SourceBranch)
    - repository: oxpd2-demos
      type: githubenterprise
      name: extensibility-2-0/oxpd2-demos
      endpoint: ghe
      ref: ${{ parameters.Demos_Branch }}
    - repository: tools
      type: githubenterprise
      name: extensibility-2-0/tools
      endpoint: ghe
      ref: ${{ parameters.Tools_Branch }}
    - repository: oxpd2-test
      type: githubenterprise
      name: extensibility-2-0/oxpd2-test
      endpoint: ghe
      ref: ${{ parameters.Test_Branch }}
    - repository: oxpd2-documentation
      type: githubenterprise
      name: extensibility-2-0/oxpd2-documentation
      endpoint: ghe
      ref: ${{ parameters.Documentation_Branch }}

trigger:
  - master
  - beta*
  - feature/*

pr:
  - master
  - beta*
  - feature/*

variables:
  - group: Packaging
  - group: Paths
  - group: PATs
  - group: Pools
  - group: SecureFiles
  - group: Versioning

pool: $(WINDOWS_POOL)

stages:
  - template: dependencies/examples_dependencies.yml@devops
